[server]
enableStaticServing = true

[client]
showSidebarNavigation = false

[[theme.fontFaces]]
family = "SpaceGrotesk"
url = "/app/static/fonts/SpaceGrotesk-VariableFont_wght.ttf"

[[theme.fontFaces]]
family = "SpaceMono"
url = "/app/static/fonts/SpaceMono-Bold.ttf"
style = "normal"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "/app/static/fonts/SpaceMono-BoldItalic.ttf"
style = "italic"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "/app/static/fonts/SpaceMono-Italic.ttf"
style = "italic"
weight = 400

[[theme.fontFaces]]
family = "SpaceMono"
url = "/app/static/fonts/SpaceMono-Regular.ttf"
style = "normal"
weight = 400

[theme]
primaryColor = "#BD97F1"
backgroundColor = "#F9F7F7EE"
secondaryBackgroundColor = "#FFF"
textColor = "#080808"
linkColor = "#0017c1d7"
borderColor = "#6060694"
showWidgetBorder = true
baseRadius = "0.65rem"
buttonRadius = "full"
font = "SpaceGrotesk"
headingFontWeights = [600,500,500,500,500,500]
headingFontSizes = ["3rem", "2rem"]
codeFont = "SpaceMono"
codeFontSize = ".75rem"
codeBackgroundColor = "#000"
showSidebarBorder = true
chartCategoricalColors = ["#0ea5e9", "#059669", "#fbbf24"]

[theme.sidebar]
backgroundColor = "#d6dfeb"
secondaryBackgroundColor = "#ecebe3"
headingFontSizes = ["1.6rem", "1.4rem", "1.2rem"]
dataframeHeaderBackgroundColor = "#e4e4e0"
